server:
  port: 7070
spring:
  application:
    name: configuracao
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabriciojacob211/meetingspringcloud.git  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      